### ISSUE TITLE
AI City Challenge

### ISSUE THREAD

**Issue by Ngoc-Nguyen-NIS** [cybercore-co-ltd/AICity2022-Track3#1]
TODO: 

1. Example data: https://drive.google.com/drive/folders/1eszwcluWPRzoJrESR9VT3xvP9CxNfhPG 

2. Result summary: https://docs.google.com/spreadsheets/d/1LvWoo9ZJpCoyqy_eYqfj9Y3dQkuEqh3-hRKI-a3VGB0/edit#gid=0

3. Dataset: 
    - [x] 1 video is divided into several videos of 3 minutes (4s overlap). Each 3m-video must have both foreground and background (Su)
    - [x]  Add more data from Kinetics (Su).
    - [x] Label data A2 (All)
    - [x] F1-Evaluation (Ngoc): https://www.aicitychallenge.org/2022-data-and-evaluation/
    - [x] Generate submission file (Vinh).
4. Feature Extraction:
    - [x] Extract offline features with backbone: ViC-T K400, I3D, TimeSformer-K400.  (Ngoc + Vinh)
    - [x] TSP- I3D, VidConv (Su Mar 29) 
    - [x] TSP - 3View concat.
    - [ ] TSP - FPN feature (interval = 2s,4s,8s)
    - [ ] Long term feature bank
5. Temporal Act Localization: 
    - [x] Intra-Inter Consistency: Chuong 
    - [ ] Add Cascade heads + Transformer Head: Ngoc 
    - [x] Learn without Forgetting: Su 
    - [ ] Use SimOTA as sampling: Chuong
    - [x] Try [PoseC3D:](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/slowonly_kinetics400_pretrained_r50_u48_120e_hmdb51_split1_keypoint.py) (Vinh)
    - [x] Feature Augment: Temporal Feature Shift. (Ngoc)
    - [x] Try ActionFormer( Transformer Neck) Ngoc
    - [x] Try AFSD (N2N single stage): https://github.com/TencentYoutuResearch/ActionDetection-AFSD
    - [x] Try BMN + Action Recognition(Vinh)
    - [ ] DaoTAD
    - [ ] add cellphone detector.
![image](https://user-images.githubusercontent.com/15174756/158510297-1d0306a1-1e76-4850-ad25-37e0c466af1b.png)

**Comment by chuong98** [comment]
![image](https://user-images.githubusercontent.com/15174756/158928320-9053b245-37ca-4242-8263-f6b41cdcb6af.png)
